import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

const firstFont = localFont({
  src: [
    { path: '../public/fonts/ttCommons/TTCommonsProTrialMedium.woff2', weight: '500', style: 'normal' },
    { path: '../public/fonts/ttCommons/TTCommonsProTrialDemiBold.woff2', weight: '600', style: 'normal' },
    { path: '../public/fonts/ttCommons/TTCommonsProTrialBold.woff2', weight: '700', style: 'normal' },
    { path: '../public/fonts/ttCommons/TTCommonsProTrialBlack.woff2', weight: '700', style: 'normal' },
  ],
  variable: '--first',
  display: 'swap'
});

const secondFont = localFont({
  src: [
    { path: '../public/fonts/ttRuns/TTRunsTrialMedium.woff2', weight: '500', style: 'normal' },
    { path: '../public/fonts/ttRuns/TTRunsTrialDemiBold.woff2', weight: '600', style: 'normal' },
    { path: '../public/fonts/ttRuns/TTRunsTrialBold.woff2', weight: '700', style: 'normal' }
  ],
  variable: '--secondary',
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${firstFont.variable} ${secondFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
